version: "3.8"
services:
  web:
    build: 
      context: .
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    network_mode: host
    restart: always
    stdin_open: true
    stop_signal: SIGINT
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock